tasks:
  - name: Install Dependencies
    init: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    command: |
      python run.py

ports:
  - port: 5000
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - ms-python.python